In [1]:
#numpy ı dahile edin 
import numpy as np

In [2]:
#5 tane 1 barındıran array oluşturun.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
#2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun

np.arange(2,100, step=2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [4]:
#5 tane 10 bulunan bir array oluşturun

np.full(5,10)

array([10, 10, 10, 10, 10])

In [5]:
#1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun

np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
#4x4'lük bir birim matris oluşturun

np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
#0 ile 7 arasında rastgele değerler üretin

a = np.random.randint(0,7)

b = np.random.randint(0,7,3) #3 tane üretin


print(a)
print(b)

5
[3 1 0]


In [8]:
#5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

np.random.randn(5,5)

array([[-1.47255439, -0.85718135,  1.98606346, -0.43151609,  1.72742256],
       [ 1.20504469,  0.13463832, -0.94491245,  0.09301467,  0.92843808],
       [-0.83709612, -0.67620374, -2.19512917, -1.06686597,  1.45218874],
       [-0.43842737,  0.61243615, -0.34730122,  1.45265851,  0.55190829],
       [ 0.39947646, -0.21559894, -0.46221052, -0.33918997, -0.82648086]])

In [9]:
#1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
#1 den 100'e kadar 10'a 10'luk bir matris üretin

arr = np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [11]:
#41 den 100'e kadar 6'ya 10'luk bir matris üretin 

arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
"""array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],              Bu görüntüyü elde etmeye çalışın.
       [ 95,  96,  97,  98,  99, 100]])                
"""
arr[6:,4:]


array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [13]:
"""
array([[ 3,  4],
       [13, 14],                 Bu görüntüyü elde etmeye çalışın.
       [23, 24]])    
"""

arrc = arr[:3,2:4]
arrc

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [14]:
"""
array([ 2, 12, 22])     Bu görüntüyü elde etmeye çalışın.

"""

arr[:3,1]

array([ 2, 12, 22])

In [15]:
"""
array([[ 2],
       [12],            Bu görüntüyü elde etmeye çalışın.
       [22]])
 
"""
arr[:3,1].reshape(3,1)

array([[ 2],
       [12],
       [22]])

In [16]:
# 10 dan 100'e kadar 10 ar 10 ar artan bir array oluşturun.

np.arange(10,110,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [17]:
#random 9 tane 0 ile 1 arasında bir değer üretin bu sayıyı 5 ile çarpın
#fakat tam kısmını alın. Bu sayılarla 3'e 3 lük matris oluşturun.

arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)


In [18]:
arr1

array([[4, 0, 4],
       [1, 3, 1],
       [4, 3, 3]])

In [19]:
arr2

array([[0, 0, 2],
       [1, 3, 2],
       [0, 2, 0]])

In [20]:
"""
Bu iki matrisinizi toplayın
"""

arr1 + arr2

array([[4, 0, 6],
       [2, 6, 3],
       [4, 5, 3]])

In [21]:
"""
Bu iki matrisinizi çarpın
"""

arr1 * arr2

array([[0, 0, 8],
       [1, 9, 2],
       [0, 6, 0]])

In [22]:
# 1. matrisinizin tüm elemanlarının ortlamasını bulun

arr1.mean()

2.5555555555555554

In [23]:
# 1. matrisinizin tüm elemanlarının toplamlarını bulun

arr1.sum()

23